# Generated by Django 5.1.15 on 2026-06-21 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='názov')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='logo')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='mena')),
                ('default_language', models.CharField(default='sk', max_length=5, verbose_name='predvolený jazyk')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktívna')),
            ],
            options={
                'verbose_name': 'prevádzka',
                'verbose_name_plural': 'prevádzky',
                'ordering': ['name'],
            },
        ),
    ]
