# Generated by Django 5.1.15 on 2026-06-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_status_reset_minutes',
            field=models.PositiveIntegerField(default=3, verbose_name='skrytie stavu objednávky (min)'),
        ),
    ]
