# Generated by Django 5.1.15 on 2026-06-21 09:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurants', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='číslo objednávky')),
                ('status', models.CharField(choices=[('new', 'Nová'), ('confirmed', 'Potvrdená'), ('in_preparation', 'Pripravuje sa'), ('ready', 'Pripravená'), ('served', 'Vydaná'), ('cancelled', 'Zrušená'), ('rejected', 'Zamietnutá')], db_index=True, default='new', max_length=20, verbose_name='stav')),
                ('source', models.CharField(choices=[('qr', 'QR'), ('tablet', 'Tablet'), ('cashier', 'Pokladňa'), ('waiter', 'Čašník')], max_length=10, verbose_name='zdroj')),
                ('customer_comment', models.TextField(blank=True, verbose_name='poznámka hosťa')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='medzisúčet')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='spolu')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='mena')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('preparation_started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='restaurants.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.diningtable')),
            ],
            options={
                'verbose_name': 'objednávka',
                'verbose_name_plural': 'objednávky',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item_name_snapshot', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Nová'), ('confirmed', 'Potvrdená'), ('in_preparation', 'Pripravuje sa'), ('ready', 'Pripravená'), ('served', 'Vydaná'), ('cancelled', 'Zrušená'), ('rejected', 'Zamietnutá')], default='new', max_length=20)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'položka objednávky',
                'verbose_name_plural': 'položky objednávky',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name_snapshot', models.CharField(max_length=150)),
                ('option_name_snapshot', models.CharField(max_length=150)),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifier_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_item_modifiers', to='menu.modifieroption')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'modifikátor položky',
                'verbose_name_plural': 'modifikátory položiek',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('new', 'Nová'), ('confirmed', 'Potvrdená'), ('in_preparation', 'Pripravuje sa'), ('ready', 'Pripravená'), ('served', 'Vydaná'), ('cancelled', 'Zrušená'), ('rejected', 'Zamietnutá')], max_length=20)),
                ('new_status', models.CharField(choices=[('new', 'Nová'), ('confirmed', 'Potvrdená'), ('in_preparation', 'Pripravuje sa'), ('ready', 'Pripravená'), ('served', 'Vydaná'), ('cancelled', 'Zrušená'), ('rejected', 'Zamietnutá')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'história stavu',
                'verbose_name_plural': 'história stavov',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
    ]
