# Generated by Django 5.1.15 on 2026-07-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_modifiergroup_menu_item_source_category'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmodifier',
            name='modifier_menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item_menu_modifiers', to='menu.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitemmodifier',
            name='modifier_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item_modifiers', to='menu.modifieroption'),
        ),
    ]
