# Generated by Django 5.1.15 on 2026-06-21 09:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='kód')),
                ('name', models.CharField(max_length=120, verbose_name='názov')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='popis')),
            ],
            options={
                'verbose_name': 'alergén',
                'verbose_name_plural': 'alergény',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_sk', models.CharField(max_length=150, verbose_name='názov (SK)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='názov (EN)')),
                ('selection_type', models.CharField(choices=[('SINGLE', 'Jeden výber'), ('MULTIPLE', 'Viacnásobný výber')], default='SINGLE', max_length=10, verbose_name='typ výberu')),
                ('min_selections', models.PositiveIntegerField(default=0, verbose_name='min. výberov')),
                ('max_selections', models.PositiveIntegerField(default=1, verbose_name='max. výberov')),
                ('is_required', models.BooleanField(default=False, verbose_name='povinné')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktívna')),
            ],
            options={
                'verbose_name': 'skupina modifikátorov',
                'verbose_name_plural': 'skupiny modifikátorov',
                'ordering': ['sort_order', 'name_sk'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_sk', models.CharField(max_length=150, verbose_name='názov (SK)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='názov (EN)')),
                ('slug', models.SlugField(max_length=150, verbose_name='slug')),
                ('description_sk', models.TextField(blank=True, verbose_name='popis (SK)')),
                ('description_en', models.TextField(blank=True, verbose_name='popis (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/categories/')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktívna')),
                ('available_from', models.TimeField(blank=True, null=True, verbose_name='dostupné od')),
                ('available_until', models.TimeField(blank=True, null=True, verbose_name='dostupné do')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'kategória',
                'verbose_name_plural': 'kategórie',
                'ordering': ['sort_order', 'name_sk'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_sk', models.CharField(max_length=200, verbose_name='názov (SK)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='názov (EN)')),
                ('slug', models.SlugField(max_length=200, verbose_name='slug')),
                ('short_description_sk', models.CharField(blank=True, max_length=255, verbose_name='krátky popis (SK)')),
                ('short_description_en', models.CharField(blank=True, max_length=255, verbose_name='krátky popis (EN)')),
                ('description_sk', models.TextField(blank=True, verbose_name='popis (SK)')),
                ('description_en', models.TextField(blank=True, verbose_name='popis (EN)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='cena')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/items/')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktívna položka')),
                ('is_available', models.BooleanField(default=True, verbose_name='momentálne dostupná')),
                ('is_featured', models.BooleanField(default=False, verbose_name='odporúčané')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('preparation_station', models.CharField(blank=True, max_length=50, verbose_name='stanica prípravy')),
                ('estimated_preparation_minutes', models.PositiveIntegerField(default=10, verbose_name='odhad prípravy (min)')),
                ('allergens', models.ManyToManyField(blank=True, related_name='items', to='menu.allergen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.menucategory', verbose_name='kategória')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'položka menu',
                'verbose_name_plural': 'položky menu',
                'ordering': ['sort_order', 'name_sk'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('is_required', models.BooleanField(default=False, verbose_name='povinné pre túto položku')),
                ('min_selections_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='min. (override)')),
                ('max_selections_override', models.PositiveIntegerField(blank=True, null=True, verbose_name='max. (override)')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_modifier_groups', to='menu.menuitem')),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='menu.modifiergroup')),
            ],
            options={
                'verbose_name': 'priradenie modifikátorov',
                'verbose_name_plural': 'priradenia modifikátorov',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='modifier_groups',
            field=models.ManyToManyField(related_name='items', through='menu.MenuItemModifierGroup', to='menu.modifiergroup'),
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name_sk', models.CharField(max_length=150, verbose_name='názov (SK)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='názov (EN)')),
                ('price_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='doplatok')),
                ('is_default', models.BooleanField(default=False, verbose_name='predvolené')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktívne')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='menu.modifiergroup')),
            ],
            options={
                'verbose_name': 'modifikátor',
                'verbose_name_plural': 'modifikátory',
                'ordering': ['sort_order', 'name_sk'],
            },
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'slug'), name='unique_category_slug_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='menuitemmodifiergroup',
            constraint=models.UniqueConstraint(fields=('menu_item', 'modifier_group'), name='unique_item_modifier_group'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'slug'), name='unique_item_slug_per_restaurant'),
        ),
    ]
