# Generated by Django 5.1.15 on 2026-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='collapsed_by_default',
            field=models.BooleanField(default=False, verbose_name='predvolene skryté (úprava zloženia)'),
        ),
    ]
