# Generated by Django 5.1.15 on 2026-07-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_modifiergroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='menu_item_source_category',
            field=models.ForeignKey(blank=True, help_text='Ak je vyplnené, skupina ponúkne aktívne položky z tejto kategórie ako doplnky.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifier_groups', to='menu.menucategory', verbose_name='položky z kategórie menu'),
        ),
    ]
