# Generated by Django 5.1.15 on 2026-06-21 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('number', models.PositiveIntegerField(verbose_name='číslo stola')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='názov')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR token')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktívny')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='poradie')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant', verbose_name='prevádzka')),
            ],
            options={
                'verbose_name': 'stôl',
                'verbose_name_plural': 'stoly',
                'ordering': ['sort_order', 'number'],
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'number'), name='unique_table_number_per_restaurant')],
            },
        ),
    ]
