# Generated by Django 5.1.15 on 2026-06-21 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100, verbose_name='akcia')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='typ objektu')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='ID objektu')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadáta')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP adresa')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'záznam denníka',
                'verbose_name_plural': 'denník akcií',
                'ordering': ['-created_at'],
            },
        ),
    ]
